### ISSUE TITLE
Crash when using minuteInterval in time picker on Huawei-devices with Android 7.0

### ISSUE THREAD

**Issue by schteff** [react-native-datetimepicker/datetimepicker#329]
This is a very specific bug, but I hope you can fix it anyway. 

It seems like Huawei devices with Android 7.0 overrides the time picker with their own variant of a "spinner". 

No other device has reported this crash. 

This spinner returns false in the ```isSpinner()``` method of the MinuteIntervalSnappableTimePickerDialog.java class. 

And when using ```minuteInterval={5}``` for example, the app crashes in the ```correctEnteredMinutes()``` method. Row 144. 

This is the spinner on these devices even when setting ```display="clock"```
![image](https://user-images.githubusercontent.com/2564884/98249484-961cbd80-1f76-11eb-8491-ada438771126.png)

We are using version 3.0.4 of datetimepicker (the latest right now). 

Our code looks like this. We have removed "minuteInterval" to solve the issue temporarily. 
```
                    <DateTimePicker
                        value={CTIME}
                        mode="time"
                        is24Hour={true}
                        display="clock"
                        onChange={(event: any, date: any) => _setTime(event, _callback, date)}
                        maximumDate={limits.max}
                        minimumDate={limits.min}
                    />
```

Stacktrace: 
```
java.lang.ClassCastException: android.widget.NumberPicker cannot be cast to android.widget.EditText
    at com.reactcommunity.rndatetimepicker.MinuteIntervalSnappableTimePickerDialog.correctEnteredMinutes(MinuteIntervalSnappableTimePickerDialog.java:144)
    at com.reactcommunity.rndatetimepicker.MinuteIntervalSnappableTimePickerDialog.onTimeChanged(MinuteIntervalSnappableTimePickerDialog.java:177)
    at com.reactcommunity.rndatetimepicker.RNDismissableTimePickerDialog.onTimeChanged(RNDismissableTimePickerDialog.java:37)
    at android.widget.TimePickerSpinnerDelegate.onTimeChanged(TimePickerSpinnerDelegate.java:485)
    at android.widget.TimePickerSpinnerDelegate.-wrap0(TimePickerSpinnerDelegate.java)
    at android.widget.TimePickerSpinnerDelegate$2.onValueChange(TimePickerSpinnerDelegate.java:140)
    at android.widget.NumberPicker.notifyChange(NumberPicker.java:2005)
    at android.widget.NumberPicker.setValueInternal(NumberPicker.java:1781)
    at android.widget.NumberPicker.scrollBy(NumberPicker.java:1169)
    at android.widget.NumberPicker.onTouchEvent(NumberPicker.java:948)
    at android.view.View.dispatchTouchEvent(View.java:10012)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2665)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2344)
    at android.widget.NumberPicker.dispatchTouchEvent(NumberPicker.java:1005)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
    at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:447)
    at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871)
    at android.app.Dialog.dispatchTouchEvent(Dialog.java:949)
    at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:409)
    at android.view.View.dispatchPointerEvent(View.java:10232)
    at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4862)
    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4723)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4255)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4308)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4274)
    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4401)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4282)
    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4458)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4255)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4308)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4274)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4282)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4255)
    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6682)
    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6656)
    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6617)
    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6809)
    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
    at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(InputEventReceiver.java)
    at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:181)
    at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6756)
    at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6837)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:926)
    at android.view.Choreographer.doCallbacks(Choreographer.java:735)
    at android.view.Choreographer.doFrame(Choreographer.java:661)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:912)
    at android.os.Handler.handleCallback(Handler.java:761)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:156)
    at android.app.ActivityThread.main(ActivityThread.java:6517)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
```

**Comment by anandchakru** [comment]
Similar strack trace on the same class, on Samsung s10, in case if this is of any help for a fix.

Happens only when I set `minuteInterval={15}` attribute in `DateTimePicker`

```
03-25 15:07:54.224 24545 24545 E AndroidRuntime: FATAL EXCEPTION: main
03-25 15:07:54.224 24545 24545 E AndroidRuntime: Process: com.rathnas.dtpicktest, PID: 24545
03-25 15:07:54.224 24545 24545 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.NumberPicker.setMinValue(int)' on a null object reference
03-25 15:07:54.224 24545 24545 E AndroidRuntime:        at com.reactcommunity.rndatetimepicker.MinuteIntervalSnappableTimePickerDialog.setSpinnerDisplayedValues(MinuteIntervalSnappableTimePickerDialog.java:248)
03-25 15:07:54.224 24545 24545 E AndroidRuntime:        at com.reactcommunity.rndatetimepicker.MinuteIntervalSnappableTimePickerDialog.setupPickerDialog(MinuteIntervalSnappableTimePickerDialog.java:234)
03-25 15:07:54.224 24545 24545 E AndroidRuntime:        at com.reactcommunity.rndatetimepicker.MinuteIntervalSnappableTimePickerDialog.onAttachedToWindow(MinuteIntervalSnappableTimePickerDialog.java:223)
03-25 15:07:54.224 24545 24545 E AndroidRuntime:        at com.reactcommunity.rndatetimepicker.RNDismissableTimePickerDialog.onAttachedToWindow(RNDismissableTimePickerDialog.java:37)
03-25 15:07:54.224 24545 24545 E AndroidRuntime:        at com.android.internal.policy.DecorView.onAttachedToWindow(DecorView.java:2371)
03-25 15:07:54.224 24545 24545 E AndroidRuntime:        at android.view.View.dispatchAttachedToWindow(View.java:22024)
03-25 15:07:54.224 24545 24545 E AndroidRuntime:        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4291)
03-25 15:07:54.224 24545 24545 E AndroidRuntime:        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3031)
03-25 15:07:54.224 24545 24545 E AndroidRuntime:        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2519)
03-25 15:07:54.224 24545 24545 E AndroidRuntime:        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9775)
03-25 15:07:54.224 24545 24545 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
03-25 15:07:54.224 24545 24545 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:809)
03-25 15:07:54.224 24545 24545 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:744)
03-25 15:07:54.224 24545 24545 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
03-25 15:07:54.224 24545 24545 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
03-25 15:07:54.224 24545 24545 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
03-25 15:07:54.224 24545 24545 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:246)
03-25 15:07:54.224 24545 24545 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8425)
03-25 15:07:54.224 24545 24545 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-25 15:07:54.224 24545 24545 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
03-25 15:07:54.224 24545 24545 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by vonovak** [comment]
@anandchakru that is a different error it seems; can you open a separate issue? thank you! :)
