### ISSUE TITLE
Picker error in the test files

### ISSUE THREAD

**Issue by gokceer** [react-native-datetimepicker/datetimepicker#624]
I have DateTimePicker in my component. After upgrading to 6.1.3, I start to get this error in my test files:

`The above error occurred in the <Picker> component:

    at Picker (/@react-native-community/datetimepicker/src/datetimepicker.ios.js:61:19)
    at View
    at View (/node_modules/react-native/jest/mockComponent.js:28:227)
    at RCTScrollView
    at RCTScrollView (/node_modules/react-native/jest/mockNativeComponent.js:15:237)
    at ScrollView (/node_modules/react-native/jest/mockScrollView.js:22:239)
    at AnimatedComponent (/node_modules/react-native/Libraries/Animated/createAnimatedComponent.js:52:227)
    at AnimatedComponentWrapper
    at View
    at View (/node_modules/react-native/jest/mockComponent.js:28:227)
    at NativeDatepicker (/components/form/datepicker/lib/index.js:26:76)
    at View
    at View (/node_modules/react-native/jest/mockComponent.js:28:227)
    at Datepicker (/components/form/datepicker/index.js:2683:35)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.`

I guess I need to add a mock function, I tried all of the mock functions in here:
https://github.com/react-native-datetimepicker/datetimepicker/issues/216
but those doesn't work for me.

Have you encountered this kind of situation?

**Comment by vonovak** [comment]
Hello and thanks for reporting,
> The above error occurred in the component:

you forgot to add the error that was reported by jest

Thank you 🙂
