### ISSUE TITLE
  The above error occurred in the <Picker> component:

### ISSUE THREAD

**Issue by vishaldhanotiyapersistent** [react-native-datetimepicker/datetimepicker#637]
I am writing the test case for date picker with jest but when I try to execute the test always receive the error.
 I am already try all the solution which are added on git issue template

This is my code snippet
```
    <DateTimePicker
            value={new Date()}
            mode={'date'}
            testID="datePicker"
            display={props.androidMode}
            onChange={onDateChange}
            minimumDate={props.minDate}
            maximumDate={props.maxDate}
          />
```
Testcase file code

```
  test('DatePicker test case', async () => {
    const {getByTestId} = await render(<DatePicker {...testDatePickerProps} />);
    let datePickerElement = getByTestId('datePicker');
    expect(datePickerElement.props.value).toBe(new Date())
  });
});
```

An error is I receive when trying to access the date picker component from the test file.

```
console.error
    The above error occurred in the <Picker> component:
   
        at Picker (D:\myproject\myapp\node_modules\@react-native-community\datetimepicker\src\datetimepicker.ios.js:46:3)
        at View
        at Component (D:\\myprojecy\myapp\node_modules\react-native\jest\mockComponent.js:28:18)       
        at View
        at Component (D:\\myproject\myapp\node_modules\react-native\jest\mockComponent.js:28:18)       
        at Pressable (D:\myproject\myapp\node_modules\react-native\Libraries\Components\Pressable\Pressable.js:174:5)
        at View
        at Component (D:\myproject\myapp\node_modules\react-native\jest\mockComponent.js:28:18)       
        at DatePicker (D:\myprojecy\myapp\src\components\inputs\DatePicker.tsx:26:53)

    Consider adding an error boundary to your tree to customize error handling behavior.
    Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
```

datetimepicker version: 6.2.0

**Comment by vonovak** [comment]
:tada: This issue has been resolved in version 6.3.0 :tada:

If this package helps you, consider [sponsoring us](https://github.com/sponsors/react-native-datetimepicker)! :rocket:
